FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

# только SSH + sudo, всё остальное поставит Ansible
RUN apt update && apt install -y \
    openssh-server \
    sudo \
    && apt clean

# пользователь ansible на тестовом сервере
RUN useradd -m -s /bin/bash ansible && \
    echo "ansible ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

# разрешаем вход по тому же ключу, что и у ansible-agent
RUN mkdir -p /home/ansible/.ssh && chmod 700 /home/ansible/.ssh
COPY ansible_agent_key.pub /home/ansible/.ssh/authorized_keys
RUN chmod 600 /home/ansible/.ssh/authorized_keys && \
    chown -R ansible:ansible /home/ansible/.ssh

RUN mkdir /var/run/sshd

EXPOSE 22 80

CMD ["/usr/sbin/sshd", "-D"]
